### ISSUE TITLE
More Incompatibility with Foo's client

### ISSUE THREAD

**Issue by abrasmag3** [sk7725/BetaMindy#105]
Crashes on startup, error window:
[img](https://celeste.is-ne.at/58SmpDRuq)

Crash log:
[crash-report-09_02_2021_16_11_57.txt](https://github.com/sk7725/BetaMindy/files/7101572/crash-report-09_02_2021_16_11_57.txt)

**Comment by sk7725** [comment]
update your....er........it is already fixed, look forward to later releases
