### ISSUE TITLE
The "Socket is Closed" issue

### ISSUE THREAD

**Issue by Mmosrup** [sk7725/BetaMindy#107]
Hello. Im MmosrupR. One of the Retired Mindustry Users. so i want to install your mod but When i wait it Pops up as "Socket is Closed." If you Can Explain to me, Please Explain in my Emails.
-MmosrupR
Email : notrigged00@gmail.com

**Comment by Mmosrup** [comment]
My device is Redmi Note 8 on my Android.

**Comment by Mmosrup** [comment]
Fun fact : I do not know how to use Github

**Comment by Goobrr** [comment]
This is not an issue with the mod, but with your internet connection (i think).

You can still install the mod manually by downloading the jar from releases and copying it into your mod folder.

**Comment by Mmosrup** [comment]
Oh. My internet is fine. But why would it disconnect
