### ISSUE TITLE
Not again.

### ISSUE THREAD

**Issue by Erisfiregamer1** [sk7725/BetaMindy#11]
(If you didn't intend this, remove the cores!)
Fired cores STILL break, and a block factory can create cores, so why do you not make them break?
Or highly nerf it and make them cost triple the materials to make them?

**Comment by Goobrr** [comment]
Why are you even firing cores in the first place.

~~also i already told sk to make the cores uncraftable, but apparently she hasn't done it yet~~

**Comment by sk7725** [comment]
see #9. This bug is now a feature. Also, you can fire 4x4 core at the 3x3 core and upgrade it.

**Comment by SMOLKEYS** [comment]
H
