### ISSUE TITLE
Crashes when I open a map

### ISSUE THREAD

**Issue by Weptlogdotzip1** [sk7725/BetaMindy#112]
**Platform**: *Android as far as I know*

**Build**: *131*

**Mod Version**: *1.05*

**Issue**: *pretty self explanatory*

**Steps to reproduce**: *pretty self explanatory too*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
give me the crash log

**Comment by USMP-lancer** [comment]
your issue is forfeit if you dont fork over the crash log sir

**Comment by Weptlogdotzip1** [comment]
> your issue is forfeit if you dont fork over the crash log sir

It was sent in discord, bro

**Comment by USMP-lancer** [comment]
send them here, dingus
