### ISSUE TITLE
Deconstructing and Reconstructing Terraformer Restores Charges

### ISSUE THREAD

**Issue by Weathercold** [sk7725/BetaMindy#114]
**Platform**: Windows

**Build**: *21949*

**Mod Version**: *v1.055*

**Issue**: *See title. This happens with presents too. Not sure if it can be fixed at all*

**Steps to reproduce**: *Deconstruct the terraformer a little bit, then reconstruct it*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

**Comment by sk7725** [comment]
Presents: yes this is an issue, true
Terraformers: you will always have insufficient resources in campaign/survival, and thus be unable to actually reconstruct it (think half-broken boulders in 6.0), so this isnt really a problem.

**Comment by Weathercold** [comment]
ok
