### ISSUE TITLE
[Crash] Cannot read field "healPercent" because "bullet" is null

### ISSUE THREAD

**Issue by Eschatologue** [sk7725/BetaMindy#131]
**Platform**: *Windows*

**Build**: *134.1*

**Mod Version**: *betamindy:1.06*

**Issue**: BetaMindy and Unlimited-Armament-Works are somehow incompatible with each other. I've already tested loading my mod with other java mods, somehow the problem only occurs with BetaMindy. 

**Steps to reproduce**: Install BetaMindy -> Install UAW -> restart the game -> Crash

**Crash logs**:  [crash-report-11_20_2021_05_51_45.txt](https://github.com/sk7725/BetaMindy/files/7573332/crash-report-11_20_2021_05_51_45.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by MrDuck557** [comment]
update your betamindy, I fixed this

**Comment by Eschatologue** [comment]
the latest in the release or from github action?

**Comment by Eschatologue** [comment]
Alrite, the thing is fixed, thanks for your assitance
