### ISSUE TITLE
wow, pistons are so useful when they dont work

### ISSUE THREAD

**Issue by Kokice5** [sk7725/BetaMindy#145]
**Platform**: Windows

**Build**: 22570

**Mod Version**: 1.09

**Issue**: When i push something with a piston, the game crashes, _although spinners (or cogs) dont crash it_

**Steps to reproduce**: Push a block

**Save file**: 

**Last log**: 

**Crash logs**: [crash-report-06_03_2022_09_33_18.txt](https://github.com/sk7725/BetaMindy/files/8830507/crash-report-06_03_2022_09_33_18.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
fixed in latest version.
