### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by DreadEthos616** [sk7725/BetaMindy#149]
**Platform**: *Android & Linux*

**Build**: *Bleeding Edge 22630*

**Mod Version**: *Beta 1.09*

**Issue**: *Crashes on startup.*

**Steps to reproduce**: *Open Mindustry with mod enabled.*

**Last log**: *{Android: [last_log.txt](https://github.com/sk7725/BetaMindy/files/8865391/last_log.txt)}* 
*{Linux: [last_log.txt](https://github.com/sk7725/BetaMindy/files/8865744/last_log.txt)}*

**Crash logs**: *{Android: [crash_1654727121018.txt](https://github.com/sk7725/BetaMindy/files/8865392/crash_1654727121018.txt)}* 
*{Linux: [crash-report-06_08_2022_17_18_28.txt](https://github.com/sk7725/BetaMindy/files/8865759/crash-report-06_08_2022_17_18_28.txt)}*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
Fixed it on latest action, see the actions tab and download the latest action.
Releases are not going to be updated until Mindustry is stable enough.
