### ISSUE TITLE
requires invalid version

### ISSUE THREAD

**Issue by az20101** [sk7725/BetaMindy#150]
i will just send screenshots to make it easy
![изображение](https://user-images.githubusercontent.com/52067229/172845366-e1d6ead1-2558-4371-98c3-50eb6dec7898.png)
![изображение](https://user-images.githubusercontent.com/52067229/172845497-3907bb32-7c64-4d5c-9650-c978021b3082.png)
![изображение](https://user-images.githubusercontent.com/52067229/172845522-ec61b48d-c78b-48c8-8df9-c0ad16e27d51.png)

**Comment by az20101** [comment]
how i am supposed to get game version 136???

**Comment by suspicious-pineapple** [comment]
https://github.com/anuken/mindustrybuilds

Not on steam though (maybe it’s possible somehow, not sure)

**Comment by rylid-umil** [comment]
anuken released erekir v7 like afew weeks ago a month idk

**Comment by rylid-umil** [comment]
go on yt how to download mindustry v7 erekir
