### ISSUE TITLE
Anubank Crash

### ISSUE THREAD

**Issue by DreadEthos616** [sk7725/BetaMindy#154]
**Platform**: *Android*

**Build**: *22808*

**Mod Version**: *Action #435*

**Issue**: *Selecting the Anubank immediately crashes the game.*

**Steps to reproduce**: *Build an Anubank, then click on it.*

**Last log**: *[last_log.txt](https://github.com/sk7725/BetaMindy/files/9078416/last_log.txt)*

**Crash logs**: *[crash_1657425413678.txt](https://github.com/sk7725/BetaMindy/files/9078418/crash_1657425413678.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by Nabstablues** [comment]
It actually breaks when you put items in the market stall

**Comment by Sharlottes** [comment]
https://github.com/sk7725/BetaMindy/commit/bb1f7c9c5398db0891caf23dd044cf29aa4819a5
