### ISSUE TITLE
Every anucoin block is broken!

### ISSUE THREAD

**Issue by Nabstablues** [sk7725/BetaMindy#156]
Platform: Android 

Build: 22818

Issue: If I put any anucoin block down my game crashes 

Steps to reproduce: When i was in campaign and i unlocked anucoins i tried to use the market stall and my game crashed, if i put down any anucoinblock that makes anucoins and a anubank down as well my game crashes. 

Crash log: /storage/emulated/0/Download/mycrash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725

**Comment by Sharlottes** [comment]
https://github.com/sk7725/BetaMindy/commit/bb1f7c9c5398db0891caf23dd044cf29aa4819a5
