### ISSUE TITLE
YOU CAN GET EREKER STUFF ON SURPULO   (YOU CAN'T USE THEM)

### ISSUE THREAD

**Issue by littlekatter330** [sk7725/BetaMindy#165]
**Platform**: *Windows 

**Build**: *139*

**Issue**: *THE ITEM SHOP HAS EREKER STUFF.*

**Steps to reproduce**: *PLACE THE ITEM SHOP THEN OPEN THE UI AND LOOK UNDER THE PRYATITE*
![20221017065627_1](https://user-images.githubusercontent.com/113895869/196161240-2e51e8cb-d5d3-4a7b-860e-103fcbe1d228.jpg)

PLEASE FIX

**Comment by sk7725** [comment]
Amazing, but also "intended"
I do have plans to make erekir blocks usable in other planets by "special" means - maybe a portal? Since some crucial payload stuff is now only available on erekir.
But yeah, its intentional for the moment.

**Comment by littlekatter330** [comment]
ok
