### ISSUE TITLE
(question) What does this mod do?

### ISSUE THREAD

**Issue by Unknow0059** [sk7725/BetaMindy#174]
Title.

The description in the in-game browser is ironically not descriptive of the mod in any meaningful way, and the readme isn't either.

I am a player who has booted into the game for the first time since my first playthrough and this is the most popular mod for reasons unknown to me and I cannot easily find out.

**Comment by sk7725** [comment]
It attempts a lot of interesting concepts such as pistons, payload turrets, spinners etc., testing the limits of Mindustry.
If you were interested in campaign content, this is not a mod you would be interested - it's more like the Create Mod of Minecraft. If that interests you, great!
You should really try it out as words hardly describe the experience, but the mod *is* also also outdated in v141 so be warned...some parts might crash the game.
