### ISSUE TITLE
Game crashing with other mods

### ISSUE THREAD

**Issue by DankMemeSys** [sk7725/BetaMindy#176]
**Platform**: *Windows 10*

**Build**: *142 (Steam)*

**Mod Version**: *Most Recent*

**Issue**: *Added some mods with BetaMindy as well, list is on log:*

**Steps to reproduce**: *enabled the mods, opened game, game crashes.*

**Crash logs**: [crash-report-02_28_2023_02_27_18.txt](https://github.com/sk7725/BetaMindy/files/10846946/crash-report-02_28_2023_02_27_18.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
fixed on latest release
