### ISSUE TITLE
v0.7 has some bugs

### ISSUE THREAD

**Issue by rmperkow** [sk7725/BetaMindy#18]
First of all, it breaks parts of [this mod](https://github.com/abomb4/super-cheat) that I use for testing.
Also, there are no names for the new walls.

**Comment by SMOLKEYS** [comment]
dont forget:

`some mods tend to not like eachother.`

**Comment by SMOLKEYS** [comment]
Back in v5, i used 2 mods at the same time:

Commandblocks
And
Unit Factory

After trying, my game went into a neverending _crashloop._

**Comment by SMOLKEYS** [comment]
Probably my device.

**Comment by sk7725** [comment]
1. Tell me what breaks, it is very unusual for a java mod to conflic with a js mod
2. oops I forgot the bundles :P

**Comment by rmperkow** [comment]
The Must Die turret and Turret turret break when placed, the other blocks like invincible walls also have this happen.
The Static Drill places right but does not work from there.
The Invincible Unit and unit spawner do not load at all.

**Comment by rmperkow** [comment]
Screenshots:
![image](https://user-images.githubusercontent.com/63563342/104254481-e582dc80-5444-11eb-8514-10397e5751f9.png)
![image](https://user-images.githubusercontent.com/63563342/104254510-f9c6d980-5444-11eb-86a6-cbaa52895af8.png)
![image](https://user-images.githubusercontent.com/63563342/104254532-0b0fe600-5445-11eb-9abd-575e08663be3.png)
Also the mega driller has no sprite

**Comment by sk7725** [comment]
> Also the mega driller has no sprite

ik

also I need your last log or something

**Comment by rmperkow** [comment]
Should be this one
[last_log.txt](https://github.com/sk7725/BetaMindy/files/5799216/last_log.txt)

**Comment by sk7725** [comment]
I have no idea at all, maybe post it on the Mindustry Issue Tracker?

**Comment by Creater3d** [comment]
I download normal artefact zip - https://github.com/sk7725/BetaMindy/actions/runs/482878805, in company mode not see mine space like volframe, chromium and other ore, it shuold be?

**Comment by GlennFolker** [comment]
> in company mode not see mine space like volframe, chromium and other ore

This is a joke.

> it shuold be and it is versiom 0.7, becouse i see jusct 0 in the end,

This is sk's fault.

**Comment by lokyinng** [comment]
IT also happen to be in v0.8

**Comment by GlennFolker** [comment]
@sk7725 forgot to change [this](https://github.com/sk7725/BetaMindy/blob/031b199f8ecfbc572b267d578448ffe616c00b52/assets/mod.json#L6).

**Comment by sk7725** [comment]
> @sk7725 forgot to change [this](https://github.com/sk7725/BetaMindy/blob/031b199f8ecfbc572b267d578448ffe616c00b52/assets/mod.json#L6).

@GlennFolker can you come up with a gradle or annotation or whatever that will auto-update that

**Comment by lokyinng** [comment]
i also found it break tester mod

**Comment by sk7725** [comment]
Also, it is a known bug that v0.7 and on kills every other JS mods in the vicinity but I really do not know what is causing this, I do not remember changing anything critical

**Comment by GlennFolker** [comment]
... but why?

**Comment by GlennFolker** [comment]
Modifying 1 line is very easy

**Comment by sk7725** [comment]
why not?

**Comment by lokyinng** [comment]
are your mod have a virus?

**Comment by lokyinng** [comment]
> are your mod have a virus?

infected

**Comment by GlennFolker** [comment]
> are your mod have a virus?

haha yes java mod is wAlWaRe

**Comment by GlennFolker** [comment]
@sk7725 I can't help you _(which is another words for **I can help you but no reason to do it**)_

**Comment by Gdeft** [comment]
Why is nobody sending any crash files or last logs.

**Comment by sk7725** [comment]
> @sk7725 I can't help you _(which is another words for **I can help you but no reason to do it**)_

help me and I will stop making your faction leader a loli

**Comment by GlennFolker** [comment]
make azurite a loli. i dare you.

**Comment by sk7725** [comment]
> are your mod have a virus?

no, what kind of a cute virus will only just touch nearby JS mods

**Comment by GlennFolker** [comment]
> > are your mod have a virus?
> 
> no, what kind of a cute virus will only just touch nearby JS mods

Kinda want to do that to bbm

**Comment by sk7725** [comment]
> Why is nobody sending any crash files or last logs.

That is in another issue or above, but I was unable to tell what the hell is wrong even after examining the logs. It even breaks non-content JS mods like timecontrol.

**Comment by lokyinng** [comment]
> > are your mod have a virus?
> 
> no, what kind of a cute virus will only just touch nearby JS mods

probaby other virus that kill js mod and java mod if infacted

**Comment by sk7725** [comment]
you have 0 IQ.

**Comment by GlennFolker** [comment]
> you have 0 IQ.

Agreed

**Comment by GlennFolker** [comment]
> First of all, it breaks parts of [this mod](https://github.com/abomb4/super-cheat) that I use for testing.
> Also, there are no names for the new walls.

Say, what contents are bugged out when you use it with this mod?

**Comment by sk7725** [comment]
> > First of all, it breaks parts of [this mod](https://github.com/abomb4/super-cheat) that I use for testing.
> > Also, there are no names for the new walls.
> 
> Say, what contents are bugged out when you use it with this mod?

the answer should be "all content with js"

**Comment by sk7725** [comment]
Can anybody test to see if JS works fine in 0.6?

**Comment by Gdeft** [comment]
~~Check if substructure works.~~

**Comment by sk7725** [comment]
According to Glenn, rhino Context is killed, somehow, and rhino fails to work

**Comment by GlennFolker** [comment]
```css
[E] java.lang.RuntimeException: No Context associated with current Thread
	at rhino.Context.getContext(Context.java:2167)
	at rhino.SecurityController.createLoader(SecurityController.java:90)
	at rhino.optimizer.Codegen.defineClass(Codegen.java:114)
	at rhino.optimizer.Codegen.createScriptObject(Codegen.java:74)
	at rhino.Context.compileImpl(Context.java:2230)
	at rhino.Context.compileString(Context.java:1291)
	at rhino.Context.compileString(Context.java:1281)
	at rhino.Context.evaluateString(Context.java:1067)
	at mindustry.mod.Scripts.run(Scripts.java:167)
	at mindustry.mod.Scripts.run(Scripts.java:159)
	at mindustry.mod.Mods.lambda$loadScripts$18(Mods.java:440)
	at arc.struct.Seq.each(Seq.java:193)
	at mindustry.mod.Mods.eachEnabled(Mods.java:576)
	at mindustry.mod.Mods.loadScripts(Mods.java:428)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:92)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:137)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
Something gave Rhino _(or even Mindustry itself)_ a stroke here, but where

**Comment by GlennFolker** [comment]
![image](https://user-images.githubusercontent.com/63218676/104538131-e175db00-564d-11eb-91fb-db7ff8cad077.png)
> Malformed

![image](https://user-images.githubusercontent.com/63218676/104538168-ef2b6080-564d-11eb-9faa-d9127bccde7e.png)

**Comment by GlennFolker** [comment]
> According to Glenn, rhino Context is killed, somehow, and rhino fails to work

~~I did not say it's killed, by the way. Just missing.~~

**Comment by Creater3d** [comment]
![image](https://user-images.githubusercontent.com/73776761/104624588-d13d1a80-56a4-11eb-9c01-39b03b68bfb4.png)
![image](https://user-images.githubusercontent.com/73776761/104624685-eade6200-56a4-11eb-8ecf-5c2da9a95c5e.png)

In the choice of items from the unloader - there is no odium, galactic alloy, which were in version 6.

**Comment by Creater3d** [comment]
![1](https://user-images.githubusercontent.com/73776761/104627151-b3bd8000-56a7-11eb-9c0e-7d372567f344.png)
![2](https://user-images.githubusercontent.com/73776761/104627155-b5874380-56a7-11eb-9aec-427870adc589.png)
![3](https://user-images.githubusercontent.com/73776761/104627156-b61fda00-56a7-11eb-9af4-7ff12da26559.png)

**Comment by sk7725** [comment]
Fixed.
