### ISSUE TITLE
I cant uninstall

### ISSUE THREAD

**Issue by Chromablade97** [sk7725/BetaMindy#180]
Windows

Release 145.1 Mindustry V7

**Mod Version**: *(optional)*

I just installed betamindy to check out all of its cool features, however when I want to uninstall betamindy to play multiplayer,  it says that "file is in use" I do everything like delete the blocks in my sectors that I played it on and the maps that I used betamindy but it still doesnt uninstall.

I did absolutely nothing to do this, I just installed betamindy.

Not sure about the save file

Not sure about this

I have one crash, its from the spyware turret, but other than that, no crash relating to the uninstalling issue

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by Austin5003** [comment]
Go to your actual mod directory and remove betamindy with the game closed

Lots of mods are affected by this issue

**Comment by Slotterleet** [comment]
Sounds like a vindovs issue

**Comment by sk7725** [comment]
This is a common issue with mods on windows. Disable the mod in mod browser, close the game, and try deleting the files (although this is not needed considering you already disabled the mod).
