### ISSUE TITLE
Linux users are the most obnoxious cunts in the world

### ISSUE THREAD

**Issue by Austin5003** [sk7725/BetaMindy#181]
Please shut the fuck up and get off your high horses just because you have no file protection, every time you people open your mouths I want to switch to linux even less

**Comment by BlueWolf3682** [comment]
sounds like im not the only one that needs some work on personal improvement

**Comment by Austin5003** [comment]
But if I improve myself then your bitching about me becomes even more invalid

**Comment by BlueWolf3682** [comment]
isnt that a good thing? anyways, not having this discussion here

**Comment by Austin5003** [comment]
So calling you a bad person is deemed (by you) as hateful towards your community
This must mean that the community is built around the negative traits that you hold, unless you're just a bad person and use them as a shield

**Comment by sk7725** [comment]
Why are yall even arguing about it here
