### ISSUE TITLE
Can not build Project

### ISSUE THREAD

**Issue by AlexanderTheGr8-gr** [sk7725/BetaMindy#190]
**Platform**: *Windows*

**Build**: *V.146*

**Issue**: *I can not manage to build/run your project in order to create the jar file of your mod.*

**Steps to reproduce**: *I tried to run gradlew locally and it failed (more on that later). Then I tried inside github. - I forked - Actions → Run Workflow → (Erekid branch) → (button) Run workflow => Result:*
```
 What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.Anuken.MindustryJitpack:core:v144.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/MindustryJitpack/core/v144/core-v144.pom
       - https://jitpack.io/com/github/Anuken/MindustryJitpack/core/v144/core-v144.pom
     Required by:
         project :
```
*Which is exactly what I found out to be the cause locally... "Could not find com.github.Anuken.MindustryJitpack:core:v144"*

**Crash logs**: *I think you can see the failed action on my fork...*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

**Comment by sk7725** [comment]
I'll ask @Anuken about it as i have no idea why the jit isn't fetching

**Comment by Anuken** [comment]
https://discord.com/channels/391020510269669376/807692120160337981/1141044571283927050
