### ISSUE TITLE
mod.json not found in the .zip

### ISSUE THREAD

**Issue by IAMROKSTAR** [sk7725/BetaMindy#2]
![Captura de pantalla (40)](https://user-images.githubusercontent.com/70150391/103007622-bc37f600-4501-11eb-818e-efe08eb6394a.png)

**Comment by Goobrr** [comment]
Bruh

**Comment by sk7725** [comment]
This is a Java mod(also known as a jar mod). 
Please consult the [README.md](https://github.com/sk7725/BetaMindy/blob/master/README.md) on how to install Java mods. 
Unlike JS mods, Java mods cannot be imported from Mindustry's menu.

*(This issue will be permanently open for FAQ purposes)*

**Comment by sk7725** [comment]
Update: now import from github/mod browser supports jar mods!
