### ISSUE TITLE
this is a suggestion, not issue lol

### ISSUE THREAD

**Issue by notMEEPoffaith** [sk7725/BetaMindy#22]
suggestion: add a tilted laser drill, which is a block that when powered, destroyes terrain tiles 3 blocks infront of it. it would be 3x3 and look like a sideways Laser Drill

cuz WHY THE FUCK NOT

**Comment by sk7725** [comment]
shut up

cuz WHY THE FUCK NOT

**Comment by QmelZ** [comment]
ah yes this is the spirit

**Comment by Gdeft** [comment]
mindustry community
