### ISSUE TITLE
Same thing with dexed...

### ISSUE THREAD

**Issue by LostCause122** [sk7725/BetaMindy#24]
![Screenshot_20210130-155259](https://user-images.githubusercontent.com/76870703/106359479-5f570900-6313-11eb-999b-3ecb99100971.png)

**Comment by LostCause122** [comment]
Sorrey for being annoying, perhaps I'm the one doing it wrong, would it be too much that you comment the steps for android install?

**Comment by LostCause122** [comment]
Tried pasting it in the mod folder with an android app tool, doesnt work, tried to use the file itself, didnt work... idk

**Comment by sk7725** [comment]
what is your Android version? It may be too low then.

**Comment by sk7725** [comment]
Also be sure to download the latest dex(v0.88)

**Comment by LostCause122** [comment]
Android version I'm sure its the latest, about the dex version, downloaded the one of the README.md link

**Comment by LostCause122** [comment]
Android 7.0 btw

**Comment by LostCause122** [comment]
Not the latest pfff

**Comment by LostCause122** [comment]
I'm highly confused, about updating Android (latest version is 11.0) it says there are no updates aviable, and the latest software/OS updates (T813 respectively) are installed

**Comment by BlueWolf3682** [comment]
![Screenshot_20210130-082606](https://user-images.githubusercontent.com/61173114/106360296-ec2ea200-62d4-11eb-8d3a-42343e93f28f.png)

my phone didnt have any issue with me importing the mod, are you sure your android version supports betamindy and that you applied the mod correctly?

**Comment by LostCause122** [comment]
My android version is 7.0, doubt its that cause I installed other jar mods, about the installation I think its the problem, not sure if I installed it correctly

**Comment by LostCause122** [comment]
What version of Android its the minimum? Just in case

**Comment by BlueWolf3682** [comment]
java version 8 is a bit old however, that may be the issue cause im pretty sure betamindy uses more modern java (though any mod for mindustry should support down to java 7, like the basegame)

**Comment by LostCause122** [comment]
Hmm

**Comment by sk7725** [comment]
BM uses java 8, I guess this means minimum Android version is 8 for java mod support.

**Comment by LostCause122** [comment]
Hmmm, must be that
