### ISSUE TITLE
Link pin crash

### ISSUE THREAD

**Issue by Goobrr** [sk7725/BetaMindy#25]
**Platform**: Android

**Build**: Release 123.1

**Mod Version**: 0.8

**Issue**: pushing a link pin with pistons causes a crash.

**Steps to reproduce**: self-explanatory.

**Save file**: [mindybug.zip](https://github.com/sk7725/BetaMindy/files/5908039/mindybug.zip)

**Crash logs**: [crashlog.txt](https://github.com/sk7725/BetaMindy/files/5908041/crashlog.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

**Comment by sk7725** [comment]
> Mod Version: 0.8

Link pins were introduced in v0.91 but okay

**Comment by sk7725** [comment]
> Java Version: 0
Java Architecture: null

the hell?

**Comment by BlueWolf3682** [comment]
my bug reports do that with java version and architecture as well.

**Comment by Goobrr** [comment]
> Link pins were introduced in v0.91 but okay

~~i didn't bother checking the version, just took a quick look at the crash log~~

**Comment by sk7725** [comment]
fixed
