### ISSUE TITLE
Ground Unit bug

### ISSUE THREAD

**Issue by notMEEPoffaith** [sk7725/BetaMindy#28]
**Platform**: *Windows*

**Build**: *steam build 123.1*

**Mod Version**: *v0.8*

**Issue**: *Ground units will move in the direction they shoot and not the direction their legs are pointing while under the affects of a Boost Pad*

**Steps to reproduce**: *I drove a ground unit on top of a boost pad and decided to shoot.*

**Save file**: *idk how do save file stuff*

**Last log**: *i dont think this is required for this issue*

**Crash logs**: *there was no crash so im not doing this*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
bug with speedmultiplier, will be revamped in the next *Mindustry* release. Refer to the trello for more details on cat waiting.
