### ISSUE TITLE
I genuinely give up on downloading this mod for a number of reasons 1) README.md does not open or work 2) if I do try to download, it crashes 3) there's not a single tutorial on how to download

### ISSUE THREAD

**Issue by fbvvbb** [sk7725/BetaMindy#30]
**Platform**: *Android//Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Mod Version**: *(optional)*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sample-text-here** [comment]
hm yes cannot open readme.md that github displays for you
![image](https://user-images.githubusercontent.com/56274831/107140719-dfafd800-68d8-11eb-8bc7-ea89f24edcce.png)

...and not even bothering to fill out the template

**Comment by sk7725** [comment]
Stick around for the next Mindustry release, where Anuke implemented Java mod import from github.

After the Mindustry update, you will now be able to download java mods from the mod browser/github imports.
