### ISSUE TITLE
Mod Window Won't Open

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [sk7725/BetaMindy#33]
**Platform**: Windows

**Build**: 124.0

**Mod Version**: Can't see

**Issue**: If I try to open the mod window, then game crashes

**Steps to reproduce**: If I try to open the mod window, then game crashes

**Last log**: [last_log.txt](https://github.com/sk7725/BetaMindy/files/5974922/last_log.txt)

**Crash logs**: [crash-report-02_13_2021_10_23_39.txt](https://github.com/sk7725/BetaMindy/files/5974921/crash-report-02_13_2021_10_23_39.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by BlueWolf3682** [comment]
This is an issue with 124.0, not BetaMindy. Update your game.
