### ISSUE TITLE
OH GOD A BUG

### ISSUE THREAD

**Issue by K6ZXS** [sk7725/BetaMindy#37]
**Platform**: Emulator(LdPlayer)

**Build**: 126.1
**Mod Version**: *(optional)*

**Issue**: *Explain your issue in detail.*
![image](https://user-images.githubusercontent.com/80146100/110198268-4ef2fa80-7e8c-11eb-86d5-428f5e6482bd.png)

**Steps to reproduce**:when i try to install the mod

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
your emulator is likely not supporting java mods. Does this happen with other java mods (ex. Sharlottes/sharustry)?
