### ISSUE TITLE
OH GOD A BUG

### ISSUE THREAD

**Issue by DXR101** [sk7725/BetaMindy#38]
**Platform**: *Android*
X
**Build**: *126.1.*
X
**Mod Version**: *latest*
X
**Issue**: *Images
![Screenshot_20210314_150049](https://user-images.githubusercontent.com/74639669/111061587-b9341c80-84d6-11eb-88c4-547f4ddbfec4.jpg)
![Screenshot_20210314_150103](https://user-images.githubusercontent.com/74639669/111061599-c5b87500-84d6-11eb-8917-3639a770f1dd.jpg)
![Screenshot_20210314_150110](https://user-images.githubusercontent.com/74639669/111061604-cfda7380-84d6-11eb-8ba9-d83a8027e8b7.jpg)
![Screenshot_20210314_150115](https://user-images.githubusercontent.com/74639669/111061616-e1238000-84d6-11eb-95c1-cff3791756bf.jpg)
![Screenshot_20210314_150121](https://user-images.githubusercontent.com/74639669/111061622-e8e32480-84d6-11eb-9f98-354eba7dc54e.jpg)
![Screenshot_20210314_150126](https://user-images.githubusercontent.com/74639669/111061629-f698aa00-84d6-11eb-982c-44e7739d0cf6.jpg)
![Screenshot_20210314_150130](https://user-images.githubusercontent.com/74639669/111061641-087a4d00-84d7-11eb-921d-893b337992a8.jpg)
![Screenshot_20210314_150135](https://user-images.githubusercontent.com/74639669/111061651-0f08c480-84d7-11eb-9421-87911044eed2.jpg)

.*
X
**Steps to reproduce**: *Installing the mod.*
X
**Save file**: *None.*
X
**Last log**:  *
[last_log.txt](https://github.com/sk7725/BetaMindy/files/6136260/last_log.txt)
.*`
X
**Crash logs**: *
[crashlog.txt](https://github.com/sk7725/BetaMindy/files/6136266/crashlog.txt)
.*
X
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by DXR101** [comment]
Other java mof work fine like ReVision(Not Promoting)

**Comment by sk7725** [comment]
@Sonnicon help

**Comment by sk7725** [comment]
Are you sure you download the jar and not the zip?

**Comment by DXR101** [comment]
> Are you sure you download the jar and not the zip?

Yes i sure

**Comment by sk7725** [comment]
> Other java mod work fine like ReVision(Not Promoting)

nvm, revision is a kotlin mod, not java (well it is but well um idk)
Tell me if other pure java mods work.

**Comment by DXR101** [comment]
> > Other java mod work fine like ReVision(Not Promoting)
> 
> nvm, revision is a kotlin mod, not java (well it is but well um idk)
> Tell me if other pure java mods work.

Like what mod?

**Comment by sk7725** [comment]
sharlottes/sharustry

**Comment by DXR101** [comment]
> sharlottes/sharustry

It didnt work too
