### ISSUE TITLE
Controlling a turret, then having a piston move it while you were controlling it doesn't move the camera

### ISSUE THREAD

**Issue by nichrosia** [sk7725/BetaMindy#39]
**Platform**: *Android//Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required.*

126.1

**Mod Version**: *(optional)*

0.9

**Issue**: *Explain your issue in detail.*

When controlling a turret, having a piston move it does not move the camera.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Open up a custom game, place down a duo and a piston, and a power source. Control the duo, then connect the power source to the piston. The camera will not have moved.

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

Not applicable, as this is a mechanic bug and a save file will do nothing.

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

Nothing was sent into the logs at the time of the bug, and the loading seems perfectly fine.

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ X **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
1. Can you still control the turret? If anything, you should have detached from the turret completely.
2. Can this be reproduced with a router?

**Comment by nichrosia** [comment]
1. No, it seems that it simply puts you in a nonexistent block, it still shows as a duo in the top-left corner, but you can't shoot or anything except for control something else.
2. Yes, it can, it puts you in the same state as the duo, except as a router

**Comment by nichrosia** [comment]
Wait, it seems to work occasionally with routers.

**Comment by nichrosia** [comment]
So it seems when there are no blocks around the router when it is pushed it will not move the camera, yet when there are blocks around it, it will move the camera, and grant control to the block. Testing to see if this works with duos/arcs too

**Comment by EmanuelG-Gaming** [comment]
> Wait, it seems to work occasionally with routers.

They're 1x1 controllable blocks but they're not turrets.

**Comment by nichrosia** [comment]
In addition, when moving a router via a flying machine, controlling it will show the highlight at the original location before it was moved

**Comment by nichrosia** [comment]
![image](https://user-images.githubusercontent.com/57579569/112724120-aca0c280-8edf-11eb-854f-1faec4715fa7.png)

**Comment by sk7725** [comment]
I guess the best solution here is to make controlled blocks unpushable.

**Comment by nichrosia** [comment]
Unfortunately, yes.
