### ISSUE TITLE
mod can't install

### ISSUE THREAD

**Issue by erSlippers** [sk7725/BetaMindy#4]
why won't Mindustry let us copy/paste the error message that's sad
have some screenshots instead
![Screenshot 2020-12-26 at 16 51 05](https://user-images.githubusercontent.com/74562376/103155794-b90b6700-479a-11eb-85b1-523e7cfe69d7.png)
![Screenshot 2020-12-26 at 16 51 16](https://user-images.githubusercontent.com/74562376/103155793-b872d080-479a-11eb-82e4-37c691acc269.png)
![Screenshot 2020-12-26 at 16 51 20](https://user-images.githubusercontent.com/74562376/103155791-b7da3a00-479a-11eb-88a7-edd25b5489a7.png)

**Comment by sk7725** [comment]
Mobile is broken. Will fix soon.

**Comment by firstcreator48** [comment]
*sad mobile player noises*

**Comment by sk7725** [comment]
Mobile is now fixed!
