### ISSUE TITLE
possible bug with linkpin?

### ISSUE THREAD

**Issue by TalphaLL** [sk7725/BetaMindy#41]
**Platform**: *Android//Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required.*
126.2

**Mod Version**: *(optional)*
v0.9

**Issue**: *Explain your issue in detail.*
link becomes desynced when moving a linkpin with a stickypiston just outside the processor's range 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

have a linkpin and processor to where they are just outside each other's range, I used a micro processor. Have a sticky piston set up to push the linkpin outside the range of the processor. Link the processor to the linkpin first, then link the linkpin to the processor. Then, just power the sticky piston, I used a button to do so. you can see it's effect when clicking on the linkpin.

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
n/a
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
so, what happens? where is the bug?

**Comment by TalphaLL** [comment]
![image](https://user-images.githubusercontent.com/31934645/113062108-73cb4c80-9170-11eb-88da-9a150dddb9db.png) this happens, each time you press the button the link gets farther away from it

**Comment by TalphaLL** [comment]
![image](https://user-images.githubusercontent.com/31934645/113062677-5945a300-9171-11eb-81c2-06752c4f257e.png)
it also disconnects itself from the processor while doing it, and reconnecting it results in multiple copies of the invalid link

**Comment by sk7725** [comment]
correct me if im wrong, but unactive links shiuldnt affect gameplay anyways.
