### ISSUE TITLE
a crash cause by spinner

### ISSUE THREAD

**Issue by bvcbvc** [sk7725/BetaMindy#45]
**Platform**: android, although it effects all platforms

**Build**: 126.2

**Mod Version**: v0.9

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: power the setup in the image
![image](https://user-images.githubusercontent.com/42185819/113598586-f5a0f700-9602-11eb-8344-98977e6dec57.png)

**Save file**: 
**Last log**: 
**Crash logs**: Mindustry has crashed. How unfortunate.
Version: release build 126.2
OS: Linux x32
Java Version: 0
Java Architecture: null
17 Mods: betamindy:0.9
[#b59e72]Demo of Chaos Itself[], dev-mode:2.3.1, test-utils:0.1, better-textures:0.0.1, classic-music:2.0, classicified:1.4, hackustry:3.3.zip, invincible-cheat-mod-v6:2.8.1, multi-lib:1.0.7, ohno-missiles:4.3, prog-mats:0.39, prog-mats-pixel-texturepack:0.0.1, purple-air:0.2.2, shitass:1, ui-lib:2.16.6, unit-factory:2.4.2, xelos-pixel-texturepack:0.4.1

> NoClassDefFoundError: 'Failed resolution of: Ljava/lang/Iterable$-CC;'
Seq.forEach: 0
RBuild.drawAll: 105
Spinner$SpinnerBuild.draw: 226
Block.drawBase: 244
BlockRenderer.drawBlocks: 261
Renderer.draw: 238
Renderer.update: 99
ApplicationCore.update: 36
ClientLauncher.update: 164
AndroidGraphics.onDrawFrame: 417
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
> ClassNotFound: 'Didn't find class "java.lang.Iterable$-CC" on path: DexPathList[[zip file "/data/app/io.anuke.mindustry-ifVaQsc-jjsXVcrKry05Kw==/base.apk"],nativeLibraryDirectories=[/data/app/io.anuke.mindustry-ifVaQsc-jjsXVcrKry05Kw==/lib/arm, /data/app/io.anuke.mindustry-ifVaQsc-jjsXVcrKry05Kw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]'
BaseDexClassLoader.findClass: 134
ClassLoader.loadClass: 379
ClassLoader.loadClass: 312
Seq.forEach: 0
RBuild.drawAll: 105
Spinner$SpinnerBuild.draw: 226
Block.drawBase: 244
BlockRenderer.drawBlocks: 261
Renderer.draw: 238
Renderer.update: 99
ApplicationCore.update: 36
ClientLauncher.update: 164
AndroidGraphics.onDrawFrame: 417
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by bvcbvc** [comment]
note that the mods i have active are dev mod and testing utils, dev mode simply enabled console, testing is for, ya know, testing, both script mods either way

**Comment by bvcbvc** [comment]
the funny part is this only occurs when it tries to render it

**Comment by sk7725** [comment]
[WIP]

**Comment by bvcbvc** [comment]
true, but its good to have bug checks for it
