### ISSUE TITLE
Unit Duct Infinite Power

### ISSUE THREAD

**Issue by Weathercold** [sk7725/BetaMindy#68]
**Platform**: *Windows*

**Build**: *126.2*

**Mod Version**: *v1.01*

**Issue**: *If you disconnect a unit duct from a power node, it remains powered and functional. Also the block status isn't working.*

**Steps to reproduce**:
*1. Build a unit duct and a power source.
2. Disconnect the unit duct from the power source.*

https://user-images.githubusercontent.com/49368953/125861664-7ad2f3d3-15ff-4d27-888c-4847d041a23e.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
note to self: updateTile, not update
