### ISSUE TITLE
Using Glass Pipes and Unit Ducts of Another Team

### ISSUE THREAD

**Issue by Weathercold** [sk7725/BetaMindy#69]
**Platform**: *Windows*

**Build**: *126.2*

**Mod Version**: *v1.01*

**Issue**: *You can use glass pipes and unit ducts of another team. When you do that, the entrance block converts to your team.*

**Steps to reproduce**: 
*1. Build a glass pipe or unit duct
2. Change Team
3. Enter the pipe*

https://user-images.githubusercontent.com/49368953/125864741-4ae01f06-d172-49e5-b7a7-ac6bc813a8a1.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by notMEEPoffaith** [comment]
haha issue #69

**Comment by Weathercold** [comment]
nice
