### ISSUE TITLE
One team's clear pipe connects with another's clear pipe

### ISSUE THREAD

**Issue by Weptlogdotzip1** [sk7725/BetaMindy#71]
**Platform**: *maybe all*

**Build**: *126.2*

**Mod Version**: *1.052*

**Issue**: *One team's clear pipe connects to another's clear pipe*

**Steps to reproduce**: *1. Install any mod that allows u to change teams. 2. Place a clear pipe on sharded. 3. Change to a different team and place a clear pipe right next to sharded's. No offset(s).*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [ ] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by lokyinng** [comment]
is that a TF2 reference

**Comment by Austin5003** [comment]
Also you can claim any team's pipe end by entering it

**Comment by sk7725** [comment]
fixed
