### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Arthur-The-Ok** [sk7725/BetaMindy#73]
![Captura de tela 2021-07-18 192151](https://user-images.githubusercontent.com/81048660/126084034-12ba26dc-27a2-4f11-bc24-12979acfd18a.jpg)
![Captura de tela 2021-07-18 192232](https://user-images.githubusercontent.com/81048660/126084036-ad2686b6-9c74-454e-9912-79cf0d3e5cc3.jpg)
![Captura de tela 2021-07-18 192249](https://user-images.githubusercontent.com/81048660/126084043-d11a58bf-3f4d-4845-a6e7-e25cf6f06aa3.jpg)
![Captura de tela 2021-07-18 192305](https://user-images.githubusercontent.com/81048660/126084047-eb28462f-73ab-4a32-87a9-844a7a3ccc01.jpg)

**Comment by sk7725** [comment]
I knew this would happen sooner or later, but this happens with mods with circulating unit trees (so it is no linger a tree)

**Comment by Arthur-The-Ok** [comment]
So all I need is to uninstall the mod that has that kind of unit tree and Betamindy will work?

**Comment by sk7725** [comment]
> So all I need to do is uninstall the mod that has that kind of unit tree and Betamindy will work??

this is a problem i should fix, but send me the mods you used so i can see if it has been fixed.

**Comment by sk7725** [comment]
fixed (probably)

**Comment by Arthur-The-Ok** [comment]
The mod still broke, but here is the list of the mods I have running:

ballgamer56/VanillaExtended
3Snake3/ADC
bloool/Aquarium
sk7725/BetaMindy
guiYMOUR/mindustry-Extra-Utilities-mod
DaGamerFiles/classic-music
bloool/CobaltMod
NewestGitHubber/Commandustry
Eschatologue/Heavy-Armaments-Industries
jhrushbe/MOARdustry
Austin5003/mohole
younggam/multi-lib
Slava0135/reVision
amg2048/saphatax
Sharlottes/sharustry
bloool/SolarWorks
sk7725/TimeControl
Eschatologue/Unlimited-Armament-Works
DeltaNedas/ui-lib
Neu1rO/Unit-Turrets
Sharlottes/UnitInfo
3Snake3/Units-mod

The ones that adds are:

guiYMOUR/mindustry-Extra-Utilities-mod
NewestGitHubber/Commandustry
Eschatologue/Heavy-Armaments-Industries
jhrushbe/MOARdustry
amg2048/saphatax
Sharlottes/sharustry
Eschatologue/Unlimited-Armament-Works
3Snake3/Units-mod

**Comment by SMOLKEYS** [comment]
dear god

**Comment by NewestGitHubber** [comment]
why did he install my mod though

**Comment by SMOLKEYS** [comment]
> why did he install my mod though

y not

**Comment by Arthur-The-Ok** [comment]
SMOLKEYS, the Mindustry God of cursedness, said "dear god" because I have too many mods?

**Comment by Austin5003** [comment]
Using my terrible mod? I'm questioning your life choices

**Comment by Arthur-The-Ok** [comment]
Austin5003, you underestimate how useful a slag extractor and the ability to dig sand from water is

**Comment by Sharlottes** [comment]
wait what sharustry is alive??

**Comment by NewestGitHubber** [comment]
> wait what shardustry is alive??
i will download and star it for you

**Comment by Arthur-The-Ok** [comment]
> wait what sharustry is alive??
Sort of, it works but blocks like the Adapt Drill crash the game

**Comment by Arthur-The-Ok** [comment]
You almost had it. The Payload Eradicator and the Payload Destroyer are fixed, but the Payload Deconstructor is still a problem

**Comment by sirgamesalot010** [comment]
I figured out what mod broke the payload deconstructor it's moardustry
