### ISSUE TITLE
2 crashes

### ISSUE THREAD

**Issue by SMOLKEYS** [sk7725/BetaMindy#74]
![SmartSelect_20210720-185208_Discord](https://user-images.githubusercontent.com/75618732/126312157-7a23644d-ae94-4b26-a99a-29106339488b.jpg)

![SmartSelect_20210720-185216_Discord](https://user-images.githubusercontent.com/75618732/126312191-10d5bb82-2975-45a1-a152-e631b99f7639.jpg)

**Comment by sk7725** [comment]
fixed
