### ISSUE TITLE
HopeBringer config crashes in v7

### ISSUE THREAD

**Issue by sk7725** [sk7725/BetaMindy#76]
**Platform**: *Android//Windows/Linux*

**Build**: *128.1*

**Mod Version**: *1.02*

**Issue**: *^*

**Steps to reproduce**: *Run control for hb*

**Save file**: *null*

**Last log**: *null*

**Crash logs**: 
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 128.1
OS: Linux xnull (aarch64)
Java Version: 0
21 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], commandustry:0.5, dev-mode:2.3.2, diversetech:0.1.0, hackustry:4, largeunits:0.1, ldb:1.3.2, new-horizon:1.8.7.1 Fix, notepad:2.0.0, override-lib:1.0.1, rtfm:2.14.10, shar:0.1, test-utils:0.14, testers:0.25, time-control:0.2, uaw:0.4, ui-lib:2.16.6, unit-factory:2.4.2, aeromindustry:1, bundles:13, classicified:1.4

> NoSuchFieldError: 'No static field configure of type Lmindustry/logic/LAccess; in class Lmindustry/logic/LAccess; or its superclasses (declaration of 'mindustry.logic.LAccess' appears in base.apk)'
MultiTurret$MultiTurretBuild.control: 120
LExecutor$ControlI.run: 546
LExecutor.runOnce: 69
LogicBlock$LogicBuild.updateTile: 433
Building.update: 1191
EntityGroup.update: 59
Groups.update: 71
Logic.update: 410
ApplicationCore.update: 37
ClientLauncher.update: 174
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by sk7725** [comment]
[reported by SMOLKEYS]

**Comment by USMP-lancer** [comment]
this issue has become stale, @sk7725 close it

**Comment by sk7725** [comment]
ah, and it was fixed in the latest actions anyways
