### ISSUE TITLE
Eu não consigo baixa o mod e nem ativar 

### ISSUE THREAD

**Issue by SrOtaku** [sk7725/BetaMindy#8]
I tried to download the mod through Github it showed this:

![Screenshot_2020-12-28-13-59-55-597_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103230955-699d7600-4915-11eb-9d2c-28ff4a2276a0.jpg)

Then I tried to download it manually, but unfortunately I couldn't:

![Screenshot_2020-12-28-14-00-22-350_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103231019-8df95280-4915-11eb-9769-ed8e00f7d39b.jpg)

I don't speak English so I translate. 
I hope you managed to understand my comment 
😅

Error details: 
![Screenshot_2020-12-28-14-13-32-972_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103231677-25ab7080-4917-11eb-89bd-248c9fe6a7b3.jpg)

**Comment by iamrocksy** [comment]
> Intenté descargar el mod a través de Github y mostró esto:
> 
> ![Screenshot_2020-12-28-13-59-55-597_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103230955-699d7600-4915-11eb-9d2c-28ff4a2276a0.jpg)
> 
> Luego intenté descargarlo manualmente, pero desafortunadamente no pude:
> 
> ![Screenshot_2020-12-28-14-00-22-350_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103231019-8df95280-4915-11eb-9769-ed8e00f7d39b.jpg)
> 
> No hablo inglés, así que traduzco.
> Espero que hayas entendido mi comentario
> 😅
> 
> Error de detalles:
> ![Screenshot_2020-12-28-14-13-32-972_io anuke mindustry](https://user-images.githubusercontent.com/76697981/103231677-25ab7080-4917-11eb-89bd-248c9fe6a7b3.jpg)

Olá!
Já passei pela mesma coisa, você experimentou o código fonte?

**Comment by iamrocksy** [comment]
lo siento, pero si mi portugues no es muy bueno es porque hablo español y utilizo el traductor
