### ISSUE TITLE
Switches.

### ISSUE THREAD

**Issue by NewestGitHubber** [sk7725/BetaMindy#87]
we have pressure plates and we have buttons so where are the switches? (note: these are just bad representations on how will they look like)
![image](https://user-images.githubusercontent.com/86703851/127853645-af9767dc-d3a1-42fe-ac34-668a9f19708f.png)

**Comment by NewestGitHubber** [comment]
top: disabled
bottom: activated

**Comment by sk7725** [comment]
logic says hello.
