### ISSUE TITLE
invasions are canceled if the only core is upgraded during one

### ISSUE THREAD

**Issue by USMP-lancer** [sk7725/BetaMindy#88]
**Platform**: *android*

**Build**: *126.1*

**Mod Version**: [this](https://github.com/sk7725/BetaMindy/actions/runs/1087449440) github action )

**Issue**: *as it says in the title, early feature invasions gameovers when core is upgraded*

**Steps to reproduce**: *start an invasion with a non upgraded core, then upgrade it, there has to be only one core(probably)*

**Save file**: *n/a*

**Last log**: *n/a*

**Crash logs**: *n/a.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by USMP-lancer** [comment]
btw when implementing the i on the alter, make sure it documents the "next:" effects

**Comment by sk7725** [comment]
intentional, upgrading the core breaches the ancient magic seal.

**Comment by USMP-lancer** [comment]
ah

**Comment by USMP-lancer** [comment]
yea that makes sense
