### ISSUE TITLE
text E N L A R G E N

### ISSUE THREAD

**Issue by NewestGitHubber** [sk7725/BetaMindy#90]
**Platform**: *Android//Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
126.2
**Mod Version**: *(optional)*
v1212
**Issue**: *Explain your issue in detail.*
All of my text decided to enlargen for no reason at all
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
There was no enemy spawn when i tried to activate the altar
![image](https://user-images.githubusercontent.com/86703851/127972112-611f144b-00a4-47f2-8000-198ff6071aaa.png)
![image](https://user-images.githubusercontent.com/86703851/127972142-2aa4b645-ce9f-407a-a687-49a59f10b52b.png)
![image](https://user-images.githubusercontent.com/86703851/127972168-0640d393-60df-4956-a84f-c811d5b01fcd.png)

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] **I have updated to the latest release (https://github.com/sk7725/BetaMindy/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725.

**Comment by NewestGitHubber** [comment]
update: it happened in-game
![image](https://user-images.githubusercontent.com/86703851/127974329-da17cb6a-8df3-4081-804b-dbee2f93780a.png)

**Comment by sk7725** [comment]
> version: v1212
*what happened*

**Comment by NewestGitHubber** [comment]
> _what happened_
apparently SMOLKEYS sent me the betamindy .jar file that has the shops, and both times i used it, the text decides to enlargen when i activated the altar
![image](https://user-images.githubusercontent.com/86703851/127990151-b762f72e-1d41-46f4-bea0-b296b5f725b5.png)
![image](https://user-images.githubusercontent.com/86703851/127990175-6eded7de-969b-45de-b007-17ed9b033346.png)

**Comment by NewestGitHubber** [comment]
the former being the v1212 version (which confused me for a bit but didn't mind it) and the latter is a fixed version that allows for item selling in the shops

**Comment by NewestGitHubber** [comment]
i think those are the latest betamindy versions except for the latter

**Comment by ThePythonGuy3** [comment]
didnt SMOLKEYS said he was breaking the jar with whatever he wanted? that can pretty much be intentional knowing him

**Comment by Toxopid82** [comment]
pffffffft lol

**Comment by Toxopid82** [comment]
also how do I get it

**Comment by ThePythonGuy3** [comment]
for the shops, just get the newest jar, and if you cant compile or get your hands on the latest jar, ask me or sth

**Comment by NewestGitHubber** [comment]
i am using a build where the shops are available to build

**Comment by SMOLKEYS** [comment]
> didnt SMOLKEYS said he was breaking the jar with whatever he wanted? that can pretty much be intentional knowing him

||how do i even mess with font sizes||

**Comment by SMOLKEYS** [comment]
> > version: v1212
> 
> _what happened_

_crap i forgot to change the version number_

**Comment by SMOLKEYS** [comment]
> > _what happened_
> > apparently SMOLKEYS sent me 2 betamindy .jar file that has the shops, and both times i used it, the text decides to enlargen when i activated the altar, i can send you those .jar files if you want
> > ![image](https://user-images.githubusercontent.com/86703851/127990151-b762f72e-1d41-46f4-bea0-b296b5f725b5.png)
> > ![image](https://user-images.githubusercontent.com/86703851/127990175-6eded7de-969b-45de-b007-17ed9b033346.png)

~~use the `_Custom` one~~

**Comment by SMOLKEYS** [comment]
the only files i mess around with is:

ShopItems.java
bundle.properties
mod.json
gradle.yml (changing zip name)

**Comment by sk7725** [comment]
does the latest action fix this bug?
