### ISSUE TITLE
uh I have issue here (AAAAAAAAAA)

### ISSUE THREAD

**Issue by Toxopid82** [sk7725/BetaMindy#98]
it crashed when the game is fully loaded
mindustry version 130
android

**Comment by Toxopid82** [comment]
eh

**Comment by MEEPofFaith** [comment]
crash report?

**Comment by sk7725** [comment]
uh i have template here (AAAAAAAAAA)

**Comment by Toxopid82** [comment]
what

**Comment by Toxopid82** [comment]
I just lost that crash log file

**Comment by Toxopid82** [comment]
when i delete the v130 and replaced it with v126.2

**Comment by Toxopid82** [comment]
mindustry
